
USE PIZZARIA;
-- SOMATÓRIO
SELECT CLI.NOME_CLIENTE
      ,PED.NUM_PEDIDO
      ,PED.DTA_HOR_ABERTURA_PEDIDO
      ,SUM(CON.QUANTIDADE * CON.PRECO) TOTAL
  FROM PIZZARIA.CLIENTE CLI
  JOIN PIZZARIA.PEDIDO PED ON CLI.COD_CLIENTE = PED.COD_CLIENTE
  JOIN PIZZARIA.CONTEM CON ON PED.NUM_PEDIDO = CON.NUM_PEDIDO
  GROUP BY CLI.NOME_CLIENTE, PED.NUM_PEDIDO, PED.DTA_HOR_ABERTURA_PEDIDO
  
SELECT CLI.NOME_CLIENTE
      ,SUM(CON.QUANTIDADE * CON.PRECO) TOTAL
  FROM PIZZARIA.CLIENTE CLI
  JOIN PIZZARIA.PEDIDO PED ON CLI.COD_CLIENTE = PED.COD_CLIENTE
  JOIN PIZZARIA.CONTEM CON ON PED.NUM_PEDIDO = CON.NUM_PEDIDO
 WHERE PED.DTA_HOR_ABERTURA_PEDIDO BETWEEN '2022-03-01 00:00:00' AND '2022-03-31 23:59:59'
 GROUP BY CLI.NOME_CLIENTE

-- MÉDIA ATITMÉTICA
SELECT CLI.NOME_CLIENTE
        ,ROUND(AVG(CON.QUANTIDADE * CON.PRECO),2) GASTO_MEDIO
    FROM PIZZARIA.CLIENTE CLI
    JOIN PIZZARIA.PEDIDO PED ON CLI.COD_CLIENTE = PED.COD_CLIENTE
    JOIN PIZZARIA.CONTEM CON ON PED.NUM_PEDIDO = CON.NUM_PEDIDO
   WHERE PED.DTA_HOR_ABERTURA_PEDIDO BETWEEN '2022-03-01 00:00:00'
                                         AND '2022-03-31 23:59:59'
   GROUP BY CLI.NOME_CLIENTE

-- CONTADOR
SELECT COUNT(DISTINCT CLI.COD_CLIENTE) QTDE
  FROM PIZZARIA.CLIENTE CLI
  JOIN PIZZARIA.PEDIDO PED ON CLI.COD_CLIENTE = PED.COD_CLIENTE
  JOIN PIZZARIA.CONTEM CON ON PED.NUM_PEDIDO = CON.NUM_PEDIDO
 WHERE PED.DTA_HOR_ABERTURA_PEDIDO BETWEEN '2022-03-01 00:00:00'
                                       AND '2022-03-31 23:59:59'

-- MENOR VALOR
SELECT CLI.NOME_CLIENTE
      ,MIN(CON.QUANTIDADE * CON.PRECO) MENOR_VALOR
  FROM PIZZARIA.CLIENTE CLI
  JOIN PIZZARIA.PEDIDO PED ON CLI.COD_CLIENTE = PED.COD_CLIENTE
  JOIN PIZZARIA.CONTEM CON ON PED.NUM_PEDIDO = CON.NUM_PEDIDO
 WHERE PED.DTA_HOR_ABERTURA_PEDIDO BETWEEN '2022-03-01 00:00:00'
                                       AND '2022-03-31 23:59:59'
 GROUP BY CLI.NOME_CLIENTE
 ORDER BY 2 DESC
  
-- MAIOR VALOR
SELECT CLI.NOME_CLIENTE
      ,MAX(CON.QUANTIDADE * CON.PRECO) MAIOR_VALOR
  FROM PIZZARIA.CLIENTE CLI
  JOIN PIZZARIA.PEDIDO PED ON CLI.COD_CLIENTE = PED.COD_CLIENTE
  JOIN PIZZARIA.CONTEM CON ON PED.NUM_PEDIDO = CON.NUM_PEDIDO
 WHERE PED.DTA_HOR_ABERTURA_PEDIDO BETWEEN '2022-03-01 00:00:00'
                                       AND '2022-03-31 23:59:59'
 GROUP BY CLI.NOME_CLIENTE
 ORDER BY 2 DESC
 

-- FILTRANDO AS COLUNAS AGRUPADAS
SELECT CLI.NOME_CLIENTE
      ,SUM(CON.QUANTIDADE * CON.PRECO) TOTAL_GASTO
  FROM PIZZARIA.CLIENTE CLI
  JOIN PIZZARIA.PEDIDO PED ON CLI.COD_CLIENTE = PED.COD_CLIENTE
  JOIN PIZZARIA.CONTEM CON ON PED.NUM_PEDIDO = CON.NUM_PEDIDO
 WHERE PED.DTA_HOR_ABERTURA_PEDIDO BETWEEN '2022-03-01 00:00:00'
                                       AND '2022-03-31 23:59:59'
 GROUP BY CLI.NOME_CLIENTE
 HAVING SUM(CON.QUANTIDADE * CON.PRECO) >= 300
 
 

 -- EXERCÍCIOS

-- EXERCÍCIOS (CORREÇÃO ÀS 20H40) INTERVALO-20H25/20H40:
1) Média de gasto por cliente no mês de abril/2021

2) Clientes que pediram pizzas com BACON e que gastaram mais de R$ 100,00

3) Pesquise todos as pizzas e o seu preço para as que utilizam mais de 3 ingredientes.

-- 1) Média de gasto por cliente no mês de abril/2021

   SELECT CLI.NOME_CLIENTE
         ,AVG(CON.QUANTIDADE * CON.PRECO) GASTO_MEDIO
     FROM PIZZARIA.CLIENTE CLI
     JOIN PIZZARIA.PEDIDO PED ON CLI.COD_CLIENTE = PED.COD_CLIENTE
     JOIN PIZZARIA.CONTEM CON ON PED.NUM_PEDIDO = CON.NUM_PEDIDO
    WHERE PED.DTA_HOR_ABERTURA_PEDIDO BETWEEN '2021-04-01 00:00:00'
										  AND '2021-04-30 23:59:59'
	GROUP BY CLI.NOME_CLIENTE
    ORDER BY 1;
    
    
-- 2) Clientes que pediram pizzas com BACON e que gastaram 
--    mais de R$ 100,00

   SELECT CLI.NOME_CLIENTE
         ,SUM(CON.QUANTIDADE * CON.PRECO) TOTAL_GASTO
	 FROM PIZZARIA.CLIENTE CLI
     JOIN PIZZARIA.PEDIDO PED ON CLI.COD_CLIENTE = PED.COD_CLIENTE
     JOIN PIZZARIA.CONTEM CON ON PED.NUM_PEDIDO = CON.NUM_PEDIDO
     JOIN PIZZARIA.INGREDIENTES_PIZZA ING ON CON.COD_PIZZA = 
                                             ING.COD_PIZZA
	WHERE ING.INGREDIENTE = 'BACON'
    GROUP BY CLI.NOME_CLIENTE
   HAVING SUM(CON.QUANTIDADE * CON.PRECO) >= 100
    ORDER BY 2 DESC;
    
-- 3) Pesquise todos as pizzas e o seu preço para 
--    as que utilizam mais de 3 ingredientes.
  SELECT PIZ.NOME_PIZZA
		,TAM.DESC_TAMANHO_PIZZA
        ,TAM.PRECO_TAMANHO_PIZZA
        ,COUNT(ING.INGREDIENTE) QTDE_INGREDIENTES
    FROM PIZZARIA.PIZZA PIZ
    JOIN PIZZARIA.INGREDIENTES_PIZZA ING ON PIZ.COD_PIZZA = 
                                            ING.COD_PIZZA
	JOIN PIZZARIA.TAMANHO_PIZZA TAM ON PIZ.COD_PIZZA = TAM.COD_PIZZA
   GROUP BY PIZ.NOME_PIZZA
           ,TAM.DESC_TAMANHO_PIZZA
           ,TAM.PRECO_TAMANHO_PIZZA
  HAVING COUNT(ING.INGREDIENTE) >= 3;
  
  
  ======================================================================================================
  
 ------------------------------- SUB SELECTS ---------------------------
 
 
  
  
  