SELECT CLI.COD_CLIENTE "Código"
      ,CLI.NOME_CLIENTE "Nome do Cliente"
      ,CLI.COD_CLIENTE + 5 CALCULO
  FROM PIZZARIA.CLIENTE CLI
  
SELECT CON.NUM_PEDIDO
      ,CON.COD_PIZZA
      ,CON.DESC_TAMANHO_PIZZA
      ,CON.QUANTIDADE
      ,CON.PRECO
      ,CON.QUANTIDADE * CON.PRECO TOTAL
  FROM PIZZARIA.CONTEM CON
  
FUNÇÕES PARA STRING
=================
SELECT CLI.COD_CLIENTE "Código"
      ,SUBSTRING(CLI.NOME_CLIENTE,5,5) "Nome do Cliente"
      ,CONCAT(LPAD(CLI.COD_CLIENTE, 6, '0'), ' - ', CLI.NOME_CLIENTE)
      ,CLI.COD_CLIENTE + 5 CALCULO
      ,CLI.IDF_SEXO
      ,CASE CLI.IDF_SEXO
			WHEN 'M' THEN 'MASCULINO'
            WHEN 'F' THEN 'FEMININO'
            ELSE 'ERRO'
	   END DESC_SEXO
	  ,CASE
			WHEN CLI.COD_CLIENTE <= 10 THEN 'VIP'
            WHEN CLI.COD_CLIENTE > 10 AND CLI.COD_CLIENTE <= 20 THEN 'ESPECIAL'
            ELSE 'OUTROS'
	   END TIPO_CLIENTE
  FROM PIZZARIA.CLIENTE CLI

SELECT SUBSTRING('ALEXANDRE LEITE RANGEL', 11, 5) SUBSTRING_
      ,LENGTH('ALEXANDRE LEITE RANGEL') LENGTH_
      ,REPLACE(REPLACE(REPLACE('UNICIDPASSAT','I','1'),'A','@'),'S','5') REPLACE_
      ,REVERSE(REPLACE(REPLACE(REPLACE('UNICIDPASSAT','I','1'),'A','@'),'S','5')) REVERSE_
      ,LOCATE('@', 'PROFALRANGEL@GMAIL.COM') LOCATE_
      ,CONCAT('UM MIL, DUZENTOS E TRINTA E QUATRO REAIS E CINQUETA E SEIS CENTAVOS', REPEAT('*', 20)) REPEAT_
      ,CONCAT('+', REPEAT('-', 78), '+') REPEAT2_
      ,CONCAT('|',SPACE(45), 'TITULO DO RELATÓRIO', SPACE(45), '|') SPACE_
      ,CONCAT('ALEX','ANDRE') CONCAT_
      ,CONCAT('|',LTRIM('          ALEXANDRE LEITE RANGEL')) LTRIM_
      ,CONCAT(RTRIM('ALEXANDRE LEITE RANGEL          '),'|') RTRIM_
      ,CONCAT('|',LTRIM(RTRIM('          ALEXANDRE LEITE RANGEL          ')),'|') TRIM_
      ,LEFT('ALEXANDRE LEITE RANGEL', 9) LEFT_
      ,RIGHT('ALEXANDRE LEITE RANGEL', 6) RIGHT_
      ,UPPER('alexandre leite rangel') UPPER_
      ,LOWER('ALEXANDRE LEITE RANGEL') LOWER_
      
FUNÇÕES PARA DATAS
==================
SELECT CURRENT_DATE DATA_HOJE
      ,CURRENT_TIME AGORA
      ,DATEDIFF(CURRENT_TIMESTAMP, '1971-04-15')/365 IDADE
      ,DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 WEEK) SUBTRAI_DATAS
      ,DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 30 HOUR) ADICIONA_DATAS
      ,CURRENT_TIMESTAMP DATA_HORA
      ,YEAR(CURRENT_TIMESTAMP) YEAR_
      ,MONTH(CURRENT_TIMESTAMP) MONTH_
      ,DAY(CURRENT_TIMESTAMP) DAY_
      ,HOUR(CURRENT_TIMESTAMP) HORA
      ,MINUTE(CURRENT_TIMESTAMP) MINUTOS
      ,SECOND(CURRENT_TIMESTAMP) SEGUNDOS
      ,WEEK(CURRENT_TIMESTAMP) SEMANA
      ,QUARTER(CURRENT_TIMESTAMP) TRIMESTRE
      
SELECT ABS(-20) VALOR_ABSOLUTO
       ,ABS(+20) valor_absoluto2
       ,ceiling(1234.56) CEILING_
       ,CEILING(1234.99) CEILING2
       ,FLOOR(1234.01) FLOOR_
       ,FLOOR(1234.99) FLOOR2_
       ,ROUND(12354.01) ARREDONDAR
       ,ROUND(12354.01) ARREDONDAR2
       ,ROUND(1234.001211544) ARREDONDAR3
       ,POWER(2, 2 )POTENCIA
       ,POWER(2, 10)POTENCIA10
       ,SQRT(4) RAIZ_QUADRADA
       ,RAND() NUMERO_RANDOMICO
       ,FLOOR (RAND()*100 ) NUMERO_RANDOMICO    
       
       
       /*
       exercício
       
       EXERCÍCIO
=========
FAÇA UMA CONSULTA NA TABELA CLIENTE QUE
RETORNE:
- A COLUNA CÓDIGO, FORMATADA COM ATÉ 10 BYTES, SENDO ZEROS À ESQUERDA
- O NOME DO CLIENTE EM LETRAS MAIÚSCULAS
- O EMAIL DO CLIENTE EM LETRAS MINÚSCULAS
- O CPF DO CLIENTE FORMATADO 99.999.999-99
- A SENHA DO CLIENTE INVERTIDA E ENCRIPTADA, SENDO:
  - 1 -> I
  - 3 -> E
  - 4 -> A
  - 5 -> S
  - 6 -> G      
     
       */
       
	SELECT CLI.COD_CLIENTE "Código"
      ,CLI.NOME_CLIENTE "Nome do Cliente"
      ,CLI.COD_CLIENTE + 5 CALCULO
	FROM PIZZARIA.CLIENTE CLI

**/resolução 1
	
  select 
	concat(lpad(cli.cod_cliente, 10,'0')) as "CodCliente"
     , upper (cli.NOME_CLIENTE) upper_ 
     , lower(cli.email) lower_ 
     , rpad(CPF,11,0)
     , concat(
			substring(rpad(CPF,11,0),1,3) , '.' ,
     		substring(rpad(CPF,11,0),4,3) , '.' ,
     		substring(rpad(CPF,11,0),7,3) , '-' ,
     		substring(rpad(CPF,11,0),10,99)) CPF
	, replace(replace(replace(replace(replace(senha,1,'I'),3,'E'),4,'A'),5,'S'),6,'G')

 from pizzaria.cliente cli
 
 
**/resolução 2

SELECT LPAD(CLI.COD_CLIENTE, 10, '0') CODIGO
      ,UPPER(CLI.NOME_CLIENTE) NOME
      ,LOWER(CLI.EMAIL) EMAIL
      ,LPAD(CLI.CPF, 11, '0') CPF_PURO
      ,CONCAT(LEFT(LPAD(CLI.CPF, 11, '0'),3),'.', 
              SUBSTRING(LPAD(CLI.CPF, 11, '0'), 4, 3), '.',
              SUBSTRING(LPAD(CLI.CPF, 11, '0'),7, 3), '-',
              RIGHT(LPAD(CLI.CPF, 11, '0'), 2)) CPF
 	  ,REVERSE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CLI.SENHA, '1', 'I'),'3','E'),'4','A'),'5','S'),'5','G')) SENHA
  FROM PIZZARIA.CLIENTE CLI
